export const HEALTH_TIMELINE = [
  {
    minutes: 20,
    key: 'blood_pressure',
    labelFr: 'Ta tension artérielle se normalise',
    bodyFr: 'La nicotine provoque une vasoconstriction immédiate. 20 min après ta dernière cigarette, les vaisseaux se relâchent et la pression redescend.',
    lifeGainedMin: 0,
  },
  {
    hours: 8,
    key: 'carbon_monoxide',
    labelFr: 'Le CO dans ton sang diminue de moitié',
    bodyFr: 'Le monoxyde de carbone bloque l\'oxygène dans tes globules rouges. En 8h, ton sang retrouve une meilleure capacité à transporter l\'oxygène.',
    lifeGainedMin: 0,
  },
  {
    hours: 24,
    key: 'heart_attack',
    labelFr: "Risque d'infarctus déjà réduit",
    bodyFr: "En 24h sans tabac, le cœur est moins sollicité, la fréquence cardiaque baisse, et les plaquettes commencent à se fluidifier. Ton risque d'infarctus diminue dès le premier jour.",
    lifeGainedMin: 11,
  },
  {
    hours: 48,
    key: 'smell_taste',
    labelFr: 'Goût et odorat commencent à revenir',
    bodyFr: 'Les terminaisons nerveuses endommagées par la fumée commencent à se régénérer. Les premiers signaux sensoriels réapparaissent dès 48h.',
    lifeGainedMin: 22,
  },
  {
    weeks: 2,
    key: 'circulation',
    labelFr: 'Circulation sanguine améliorée',
    bodyFr: 'La microcirculation dans les extrémités (mains, pieds) est nettement meilleure. L\'effort physique devient plus facile et moins essoufflant.',
    lifeGainedMin: 110,
  },
  {
    months: 1,
    key: 'lungs',
    labelFr: 'Poumons : cils régénérés, moins de toux',
    bodyFr: 'Les cils bronchiques — paralysés par la fumée — reprennent leur mouvement. Ils évacuent les mucosités, réduisent la toux et les infections respiratoires.',
    lifeGainedMin: 330,
  },
  {
    months: 3,
    key: 'fertility',
    labelFr: 'Fertilité améliorée',
    bodyFr: "Le tabac réduit la fertilité chez la femme et la qualité du sperme chez l'homme. À 3 mois, ces paramètres reviennent à des valeurs proches de la normale.",
    lifeGainedMin: 990,
  },
  {
    months: 9,
    key: 'breathing',
    labelFr: 'Respiration nettement plus facile',
    bodyFr: "La capacité pulmonaire augmente de 5 à 10%. Les infections des voies respiratoires sont deux fois moins fréquentes. L'essoufflement à l'effort disparaît progressivement.",
    lifeGainedMin: 2970,
  },
  {
    years: 1,
    key: 'heart_disease',
    labelFr: 'Risque de maladie coronaire divisé par 2',
    bodyFr: "Après un an sans fumer, le risque d'infarctus du myocarde est réduit de moitié par rapport à un fumeur. Le système cardiovasculaire continue de se réparer.",
    lifeGainedMin: 5500,
  },
  {
    years: 5,
    key: 'stroke',
    labelFr: "Risque d'AVC identique à un non-fumeur",
    bodyFr: "En 5 ans, le risque d'accident vasculaire cérébral rejoint celui d'une personne n'ayant jamais fumé. La paroi des artères s'est significativement régénérée.",
    lifeGainedMin: 27500,
  },
  {
    years: 10,
    key: 'lung_cancer',
    labelFr: 'Risque de cancer du poumon divisé par 2',
    bodyFr: "Le risque de cancer du poumon est réduit de 50% par rapport à un fumeur actif. Le risque de cancer de la bouche, de l'œsophage et de la vessie baisse aussi fortement.",
    lifeGainedMin: 55000,
  },
  {
    years: 15,
    key: 'heart_normal',
    labelFr: 'Risque cardiaque identique à un non-fumeur',
    bodyFr: "À 15 ans, le risque de maladie coronaire est équivalent à celui d'une personne n'ayant jamais fumé. L'arrêt du tabac a effacé presque toutes les séquelles cardio-vasculaires.",
    lifeGainedMin: 82500,
  },
] as const;

export type HealthTimelineItem = (typeof HEALTH_TIMELINE)[number];
